[package]
name = "project"
version = "0.1.0"
edition = "2021"

[lib]
name = "cryptoapi"
crate-type = ["staticlib"]

[dependencies]
sha3 = "0.10.8"
sha2 = "0.10.8"
digest = "0.10.7"
static_assertions = "1.1"

[build-dependencies]
cbindgen = "0.26.0"
